#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

echo "==> Updating..."
script/update

AWS_PROFILE=${AWS_PROFILE:-dalmatian}

echo "==> Finding Dalmatian config..."
CI_PIPELINE=$(aws codepipeline get-pipeline --name ci-terraform-build-pipeline --profile "$AWS_PROFILE")
CI_BUILD_PROJECT_NAME=$(echo "$CI_PIPELINE" | jq -r '.pipeline.stages[] | select(.name == "Build") | .actions[] | select(.name == "Build-ci") | .configuration.ProjectName')

BUILD_PROJECTS=$(aws codebuild batch-get-projects --names "$CI_BUILD_PROJECT_NAME" --profile "$AWS_PROFILE")
DALMATIAN_CONFIG_REPO=$(echo "$BUILD_PROJECTS" | jq -r '.projects[0].environment.environmentVariables[] | select(.name == "dalmatian_config_repo") | .value')

echo "==> Fetching Dalmatian config..."
mkdir -p tmp
rm -rf tmp/dalmatian-config
git clone "$DALMATIAN_CONFIG_REPO" tmp/dalmatian-config

echo "==> Populating the MongoDB with Dalmatian config..."
bundle exec rake populate_database

echo "==> Starting the development server..."
bundle exec rails server
