#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

if ! [ "$(command -v dalmatian)" ]
then
  echo "Warning: Dalmtian Tools are not installed"
  echo "         To authenticate with AWS it is required to install and run"
  echo "         \`dalmatian login\` rather than managing the AWS credentials"
  echo "         Install from: https://github.com/dxw/dalmatian-tools"
  exit 1
fi

echo "==> Updating..."
script/update

AWS_PROFILE=${AWS_PROFILE:-dalmatian-admin}

echo "==> Finding Dalmatian config..."
CI_PIPELINE=$(dalmatian aws exec -i test-app codepipeline get-pipeline --name ci-terraform-build-pipeline | sed '/==>/d')
CI_BUILD_PROJECT_NAME=$(echo "$CI_PIPELINE" | jq -r '.pipeline.stages[] | select(.name == "Build") | .actions[] | select(.name == "Build-ci") | .configuration.ProjectName')

BUILD_PROJECTS=$(dalmatian aws exec -i test-app codebuild batch-get-projects --names "$CI_BUILD_PROJECT_NAME" | sed '/==>/d')
DALMATIAN_CONFIG_REPO=$(echo "$BUILD_PROJECTS" | jq -r '.projects[0].environment.environmentVariables[] | select(.name == "dalmatian_config_repo") | .value')

echo "==> Fetching Dalmatian config..."
mkdir -p tmp
rm -rf tmp/dalmatian-config
git clone "$DALMATIAN_CONFIG_REPO" tmp/dalmatian-config

echo "==> Populating the MongoDB with Dalmatian config..."
dalmatian util exec -i test-app bundle exec rake populate_database

echo "==> Starting the development server..."
dalmatian util exec -i test-app bundle exec rails server
