#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

cd "$(dirname "$0")/.."

if [ -d vendor/bundle ]; then
  echo "==> Cleaning installed Ruby dependencies..."
  git clean -x --force -- vendor/bundle
fi

echo "==> Bootstrapping..."
script/bootstrap

if [ ! -f .env.development.local ]; then
  echo "==> Copying default environment config..."
  cp .env.example .env.development.local
fi

echo "==> Dropping database..."
bundle exec rails db:drop

echo "==> Starting Mongo database..."
brew services start mongodb-community@4.4

echo "==> Creating database..."
bundle exec rails db:setup

echo "==> Running database migrations..."
bundle exec rails db:migrate
