name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run the tests
        run: docker-compose -f docker-compose.test.yml run web script/test
